# Generated by Django 5.0.4 on 2026-05-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAIL', 'Login failure'), ('VOTE_CAST', 'Vote cast'), ('VOTE_DUPLICATE', 'Duplicate vote attempt'), ('ADMIN_ACTION', 'Admin action'), ('ANOMALY', 'ML anomaly detected'), ('INJECTION_ATTEMPT', 'Injection attempt'), ('BLOCKED_IP', 'Blocked IP access')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('rule_triggered', models.BooleanField(default=False)),
                ('rule_name', models.CharField(blank=True, max_length=100)),
                ('rule_score', models.IntegerField(default=0)),
                ('ml_anomaly_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('action_taken', models.CharField(choices=[('ALLOW', 'Allow'), ('ALERT', 'Alert'), ('BLOCK', 'Block')], default='ALLOW', max_length=10)),
                ('iso_control', models.CharField(blank=True, max_length=20)),
                ('nist_category', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='ids_engine__ip_addr_874fe1_idx'), models.Index(fields=['risk_level', 'timestamp'], name='ids_engine__risk_le_875f39_idx')],
            },
        ),
    ]
